# Generated by Django 4.2.29 on 2026-03-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0001_initial'),
        ('user', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourhoodData',
            fields=[
                ('ndvi', models.FloatField(default=0)),
                ('neighbourhood_name', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('geoJSON', models.JSONField(verbose_name='geoJSON')),
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerInNeighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_to_neighbourhood_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='flower.flowerdata')),
                ('neighbourhood_to_flower_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
        migrations.CreateModel(
            name='EventsInNeighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_to_neightbourhood_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventdata')),
                ('neighbourhood_to_event_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_to_neighbourhood_fk', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
                ('neighbourhood_to_member_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhooddata')),
            ],
        ),
    ]
