# Generated by Django 4.2.29 on 2026-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerData',
            fields=[
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(default='', max_length=100)),
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
